# Generated by Django 4.0.4 on 2022-05-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='product_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='p_id',
        ),
    ]
