# Generated by Django 4.0.4 on 2022-05-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_id_photo_p_id_rename_id_product_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='p_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brief_description',
            new_name='p_brief_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail_description',
            new_name='p_detail_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='large_category',
            new_name='p_large_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='medium_category',
            new_name='p_medium_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pet',
            new_name='p_pet',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_count',
            new_name='p_product_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='retail_price',
            new_name='p_retail_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category1',
            new_name='p_small_category1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category2',
            new_name='p_small_category2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category3',
            new_name='p_small_category3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category4',
            new_name='p_small_category4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category5',
            new_name='p_small_category5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category6',
            new_name='p_small_category6',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category7',
            new_name='p_small_category7',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_category8',
            new_name='p_small_category8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wholesale_price',
            new_name='p_wholesale_price',
        ),
    ]
