# Generated by Django 4.0.4 on 2022-05-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_rename_u_id_user_u_strid_remove_user_u_shopping_cart'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_count', models.IntegerField(default=1)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
