# Generated by Django 4.0.4 on 2022-05-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_id',
            new_name='u_strid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_shopping_cart',
        ),
    ]
