# Generated by Django 4.0.4 on 2022-05-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_u_id_user_u_strid_remove_user_u_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='u_id',
        ),
    ]
